### ISSUE TITLE
Channel Number and Suggestion (if possible)

### ISSUE THREAD

**Issue by LordDeimos666** [cr4ckp0t/AnnounceRare#1]
Hello, for those that have ElvUI, channel n.1 is for addon comm (**ElvUIGVC**) and not the general zone one.

Can you make it a parameter to pass for the channel number to send the message without modifing the LUA code?

Also if the rare is not engaged, and always on the target is it possible to announce when that is engaged automaticly without using the macro again with a shot message like "rare is engaged now" or "rare dead".

Regards

**Comment by cr4ckp0t** [comment]
I use ElvUI and it has not been an issue as far as channel numbers go, but I will see if I can have it determine the appropriate channel to use. Alternatively, I may also include a way to customize which channel to use (say, yell, party, guild, etc.).

**Comment by LordDeimos666** [comment]
Managed to get the channel general to n. 1 dunno why the channel wasn't saved as 1. But the option to report in wich channel like you said it's a good one also :)
