### ISSUE TITLE
Urduu is Not Announced / Unable to Announce Rares Twice in Same Day

### ISSUE THREAD

**Issue by Fynzou** [cr4ckp0t/AnnounceRare#10]
Title. Urduu for some reason is a Gold Dragon portrait rather than a Silver Dragon, despite being a rare spawn. (and needed for the Achievement to kill all the rares). As such, he is not announced when you target him, nor can you manually announce him by typing /rare. 

I'm not entirely sure, but I think the same issue happens with one of the other Coral Ancient Rares. (Anemonar? Maybe Kelpwillow?) 

And on a second note, is there a reason we can't manually announce a rare we've already seen/killed for the day, for other people in the zone? Like I was passing by Carnivorous Lasher today and I tried to announce it even though I didn't need it to let others know it was up, but the addon refused to let me. 

Like, why not just enable a 30 minute waiting period between allowing you to announce the same rare or something?

**Comment by cr4ckp0t** [comment]
The rares are no longer considered rare when you kill them until reset and unit classification is how the addon determines what is a rare. It does not go based on a list of possible NPCs (except for specific ones for naming reasons).

Urduu I am unsure as to why it doesn't trigger. The addon triggers when the mob is a rare or rare elite, so if it does not qualify as either of those, then it will not trigger.

**Comment by Fynzou** [comment]
Urduu spawns as a Gold Dragon, rather than a Silver Dragon, which is why he doesn't announce/can't be announced. So if possible, you might need to add him to the list of possible NPCs?

**Comment by Fynzou** [comment]
And to add on to the ticket you closed yesterday, I also have the same issue he had, ANY rare in Nazjatar/Mechagon refuses to manually announce when you type /rare anymore. No dialogue pops up at all. The only dialogue you get when you type /rare anymore is if you're targeting something that isn't a rare. 

(That's the second issue I mentioned in this ticket)

**Comment by Fynzou** [comment]
I just double checked in game. Anemonar also spawns as a gold dragon like Urduu and as such is not announced nor can he be announced.

**Comment by cr4ckp0t** [comment]
I'll try to catch one to see what its classification is.

**Comment by cr4ckp0t** [comment]
Okay, I can confirm Urduu is just an elite mob, not classified as rare. So that's why it will not announce it. I will put in some custom bypass for it to trigger on these mobs.
