### ISSUE TITLE
typing /rare to announce a rare manually doesn't seem to function anymore

### ISSUE THREAD

**Issue by penguinsane** [cr4ckp0t/AnnounceRare#11]
title. Typing /rare doesn't yield advertised results anymore.

**Comment by cr4ckp0t** [comment]
Not enough information.

What mob? What zone? What, if anything does it do?

Closing ticket.

**Comment by penguinsane** [comment]
Any mob, Nazjatar or Mechagon, and it does nothing. No errors given. Just doesn't re-announce to output anymore if you want to do it manually. There wasn't more info in the ticket because there is no more info.

**Comment by Gershuun** [comment]
Second this, was just gonna try completely re-installing the addon. /rare to manually call out a rare hasnt worked for me in weeks either.

edit: Fresh reload manual /rare doesnt announce
![image](https://user-images.githubusercontent.com/52564384/62021254-ee69ea80-b18b-11e9-963d-6e18fb1634e4.png)
