### ISSUE TITLE
Monitoring other messages to avoid Spamming General

### ISSUE THREAD

**Issue by inzomniack** [cr4ckp0t/AnnounceRare#12]
Would be great if it could monitor General chat, and if someone else using the same addon sends an alert for a mob, it does not trigger your alert.

As more and more people use the addon, im starting to see general get filled up with spam from 4-5 people per rare, and then the obligatory 5 immediate spams when it dies

**Comment by cr4ckp0t** [comment]
That is a planned feature in 1.2.0, which will hopefully be coming in the next week or so. I am going to have it check for multiple addons, since there are a few that I'm aware of.
