### ISSUE TITLE
Scrap King - Announces death during resurrection / Full health heal

### ISSUE THREAD

**Issue by inzomniack** [cr4ckp0t/AnnounceRare#13]
A few people called me a liar for broadcasting scrap king death :)

I dont care that much, figured i;d report it in case you could code for him it had to hit 0% twice to announce death or something similar.

**Comment by cr4ckp0t** [comment]
It is supposed to skip Scrap King's first (mounted) death and only announce when he actually dies. His is a bit trickier, so I must not have gotten it right, I'll take a look.
