### ISSUE TITLE
error

### ISSUE THREAD

**Issue by BlueNightSky** [cr4ckp0t/AnnounceRare#14]
1x AnnounceRare\AnnounceRare-1.1.10.lua:416: attempt to index local 'value' (a nil value)
AnnounceRare\AnnounceRare-1.1.10.lua:416: in function `?'
FrameXML\ChatFrame.lua:4836: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4497: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4533: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
args = "output"
key = "output"
_ = "output"
value = nil
(*temporary) = "output"
(*temporary) = nil
(*temporary) = 1
(*temporary) = nil
(*temporary) = "([| ])"
(*temporary) = "o"
(*temporary) = "output"
(*temporary) = nil
(*temporary) = 1000000000
(*temporary) = 1000000000
(*temporary) = 1
(*temporary) = nil
(*temporary) = "attempt to index local 'value' (a nil value)"
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 Enable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:85
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 CHAT_MSG_MONSTER_EMOTE = <function> defined @AnnounceRare\AnnounceRare.lua:308
 UnregisterComm = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 defaultModuleLibraries = <table> {
 }
 UnregisterChatCommand = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:111
 CreateWaypoint = <function> defined @AnnounceRare\AnnounceRare.lua:214
 Printf = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 correctZone = true
 tomtomExpire = false
 name = "AnnounceRare"
 lastArmory = 0
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 orderedModules = <table> {
 }
 lastWaypoint = false
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 tomtom = false
 rares = <table> {
 }
 UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 CheckZone = <function> defined @AnnounceRare\AnnounceRare.lua:241
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 GetArgs = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:144
 Print = <function> defined @AnnounceRare\AnnounceRare.lua:255
 baseName = "AnnounceRare"
 OnInitialize = <function> defined @AnnounceRare\AnnounceRare.lua:459
 PLAYER_ENTERING_WORLD = <function> defined @AnnounceRare\AnnounceRare.lua:351
 UPDATE_MOUSEOVER_UNIT = <function> defined @AnnounceRare\AnnounceRare.lua:295
 SendCommMessage = <function> defined @Ace3\AceComm-3.0\AceComm-3.0.lua:87
 db = <table> {
 }
 SetDefaultModuleState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:387
 PLAYER_TARGET_CHANGED = <function> defined @AnnounceRare\AnnounceRare.lua:259
 UnregisterAllComm = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 version = "1.1.10"
 enabledState = true
 COMBAT_LOG_EVENT_UNFILTERED = <function> defined @AnnounceRare\AnnounceRare.lua:270
 RegisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 RegisterComm = <function> defined @Ace3\AceComm-3.0\AceComm-3.0.lua:60
 SendMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:59
 UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 IterateModules = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:437
 NewModule = <function> defined @Ace3\AceAddon-3.0\AceA

**Comment by cr4ckp0t** [comment]
It is an unintended issue, but the output option is not designed to be used without a follow up parameter. That is the reason for the error. Could have sworn I put in a check to prevent this sort of behavior, but I can duplicate. I will get it fixed. Thanks!

**Comment by cr4ckp0t** [comment]
Fixed in 1.1.11.
