### ISSUE TITLE
Will not automatically announce rare, and still have errors

### ISSUE THREAD

**Issue by BlueNightSky** [cr4ckp0t/AnnounceRare#17]
The announce is completely unresponsive, and there is no response at the time of death. There is an error in the input command.
This addon has been unable to properly announce, I want to give up...

3x AnnounceRare\AnnounceRare-1.1.11.lua:372: invalid option in `format'
[C]: in function `format'
AnnounceRare\AnnounceRare-1.1.11.lua:372: in function `?'
FrameXML\ChatFrame.lua:4836: in function `ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4497: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4533: in function `ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

Locals:
(*temporary) = "自動通告已經 %S！"
(*temporary) = "|cff00ff00啟用|r"

**Comment by cr4ckp0t** [comment]
I have fixed the issue in 1.1.12 with not announcing with the command. You said there's an error in the "input" command, but I assume you mean the output. Give what's below, I assume you're using a non-English localized client? I suspect this is the reason for the error since the addon is not currently setup to use localized language in the commands. I have added it, but have no way to test it.

I will upload 1.1.12-beta to Curse to see if it fixes the issue with localized commands and the manual announcements.

**Comment by cr4ckp0t** [comment]
1.1.12-beta has been pushed to curse. Once approved by their moderators, install it and test to see if the issues persist. I am at work right now, so I am unable to test myself.

Thank you for the reporting the issue!

**Comment by BlueNightSky** [comment]
yes , I mean the output. and yes I using a non-English localized client.
Thank you for your hard work, I will try again if I have time.

**Comment by BlueNightSky** [comment]
There are still errors, and still can't be announce automatically.

`3x AnnounceRare\AnnounceRare-1.1.12-beta.lua:228: attempt to call global 'FindInArry' (a nil value)
AnnounceRare\AnnounceRare-1.1.12-beta.lua:228: in function <AnnounceRare\AnnounceRare.lua:211>
AnnounceRare\AnnounceRare-1.1.12-beta.lua:281: in function `?'
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `TurnOrActionStop'
[string "TURNORACTION"]:4: in function <[string "TURNORACTION"]:1>`

**Comment by cr4ckp0t** [comment]
Just a simple typo. You can either grab beta2 from Curse (when it is approved) or manually edit AnnounceRare.lua in the AnnounceRare folder of your AddOns folder of WOW to make the fix.

On line 228 replace `FindInArry` with `FindInArray`. Save, reload UI (if in game), and it should be good to test.

**Comment by BlueNightSky** [comment]
Use the latest beta version.
No errors were found, but it is still not announced, and the command is completely unresponsive.

Thank you for your hard work, but still have not found the crux of the problem, maybe it is a problem with non-English clients, I have been a little too lazy to test (have never worked properly)

**Comment by cr4ckp0t** [comment]
Yeah I can't really answer since I don't use a non-English client. I know the addon works as expected for en-US clients, beyond that I can't really say.
