### ISSUE TITLE
Suggestion: add death message

### ISSUE THREAD

**Issue by Daenarys** [cr4ckp0t/AnnounceRare#2]
Would be nice if you could add something like: 

Rare: Mr.Fixthiss has died.

Whenever the rare gets killed

**Comment by Daenarys** [comment]
I mean, announce that message in the general chat when a rare dies.

**Comment by LordDeimos666** [comment]
That's a semi duplicate of mine #1 since i also suggested it.

**Comment by cr4ckp0t** [comment]
I have already started working on that. Gotta relearn how to watch the combat log events. ;-) Going to close this request and work off of #1.
