### ISSUE TITLE
AnnounceRare announces World Bosses as rare mobs

### ISSUE THREAD

**Issue by Sinnoh** [cr4ckp0t/AnnounceRare#20]
The Addon announces Ulmath, Moon Priestess Liara, Guardian Tyr'Mar and Wekemara (Nazjatar World-Bosses) as rare mobs. The Mobs may appear as rare mob (silver border), but i would not count them as rare mobs and in my opinion, the addon should not announce

**Comment by cr4ckp0t** [comment]
It is doing how it was written to function, so it's not a bug or anything. I could fix it, but in 2.0.0 it will only announce the rares in its database, so I do not plan on changing anything in the 1.x branch.
