### ISSUE TITLE
Addon commands not working in game

### ISSUE THREAD

**Issue by Izlandia** [cr4ckp0t/AnnounceRare#24]
Hi I i just downloaded this.  It's installed and loaded in wow and shows up in the addon menu with the yellow checkmark next to it.

When I type any of the commands in game I just receive an error that says, "Type '/help' for a listing of a few commands."

I have tried having a rare selected and also not selected when trying to type the commands.  I am in Vale during the mantid invasion.

Thanks for your help.

**Comment by cr4ckp0t** [comment]
The chat command definitely works. What command are you trying to run?

Try: `/rare help`

**Comment by Izlandia** [comment]
I've tried them all today and keep getting the same message over and over.

**Comment by cr4ckp0t** [comment]
You must not have installed the addon properly, because it works for me as well as some of my guildmates who installed it via the Twitch app.

**Comment by ghost** [comment]
I have the exact same issue, not sure why it's not working since the addon did work for me previously.

I will do some investigations, starting with disabling all other addons and enabling them one by one, once done I will report back my findings here.

**Comment by ghost** [comment]
@cr4ckp0t 

I'm still not able to get this addon to work, I have tried a clean installation of both WoW with only the AnnounceRare addon installed but it still does not work. I installed the addon using Twitch.

**Error logs below:**

```
Date: 2020-03-07 10:58:20
ID: 1
Error occured in: Global
Count: 1
Message: ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua line 7:
   Cannot find a library instance of "AceGUI-3.0".
Debug:
   [string "=[C]"]: error()
   [string "@!Swatter\Support\LibStub.lua"]:23: LibStub()
   [string "@AnnounceRare\Libraries\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:7: in main chunk
Locals:
(*temporary) = "Cannot find a library instance of "AceGUI-3.0"."

AddOns:
  Swatter, v8.3.BETA-4-4 (NzothsFolly)
  AnnounceRare, v2.0.6
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=98)
```

```
Date: 2020-03-07 10:58:20
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\AnnounceRare\AnnounceRare.lua line 648:
   Cannot find a library instance of "AceConfigDialog-3.0".
Debug:
   [string "=[C]"]: error()
   [string "@!Swatter\Support\LibStub.lua"]:23: LibStub()
   [string "@AnnounceRare\AnnounceRare.lua"]:648:
      AnnounceRare\AnnounceRare.lua:644
   [string "=[C]"]: ?
   [string "@AnnounceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70:
      ...nceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65
   [string "@AnnounceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:498: InitializeAddon()
   [string "@AnnounceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:613:
      ...nceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:605
Locals:
None
AddOns:
  Swatter, v8.3.BETA-4-4 (NzothsFolly)
  AnnounceRare, v2.0.6
  BlizRuntimeLib_enUS v8.3.0.80300 <none>
  (ck=98)
```
