### ISSUE TITLE
Can't announce rare

### ISSUE THREAD

**Issue by GODLIKE-ro** [cr4ckp0t/AnnounceRare#25]
after the last reset i cant announce rares anymore when i target a rare and type /rare. my girlfriend also tried doing the same but it didnt work for her too.

**Comment by lucasrdonato** [comment]
I am also having this issue!

I also keep getting error messages when I click on chat channels:

Message: Interface\AddOns\AnnounceRare\AnnounceRare.lua:270: bad argument #3 to 'format' (string expected, got nil)
Time: Sat Apr 25 11:31:04 2020
Count: 1
Stack: Interface\AddOns\AnnounceRare\AnnounceRare.lua:270: bad argument #3 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@Interface\AddOns\AnnounceRare\AnnounceRare.lua"]:270: in function <Interface\AddOns\AnnounceRare\AnnounceRare.lua:266>
[string "=(tail call)"]: ?
[string "@Interface\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua"]:3520: in function <...ace\AddOns\Blizzard_CombatLog\Blizzard_CombatLog.lua:3461>
[string "=[C]"]: in function `SetItemRef'
[string "@Interface\FrameXML\ChatFrame.lua"]:3735: in function `ChatFrame_OnHyperlinkShow'
[string "*:OnHyperlinkClick"]:1: in function <[string "*:OnHyperlinkClick"]:1>

Locals: (*temporary) = "Link Type: %s, ID: %s, Health: %s, Max: %s"
(*temporary) = "channel"
(*temporary) = "GUILD"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by Tequima** [comment]
With debug running, getting AR2 Log: Invalid ID provided for example on Bonepicker.

Still getting the Death Announce prompt. This works. Except when debug is running when I get a LUA error:

1x AnnounceRare\AnnounceRare-2.0.7.lua:270: bad argument #3 to 'format' (string expected, got nil)
[string "=[C]"]: in function `format'
[string "@AnnounceRare\AnnounceRare-2.0.7.lua"]:270: in function <AnnounceRare\AnnounceRare.lua:266>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetItemRef'
[string "@FrameXML\ChatFrame.lua"]:3735: in function `ChatFrame_OnHyperlinkShow'
[string "*:OnHyperlinkClick"]:1: in function <[string "*:OnHyperlinkClick"]:1>

Locals:
(*temporary) = "Link Type: %s, ID: %s, Health: %s, Max: %s"
(*temporary) = "AR2_DEATH"
(*temporary) = "152001"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "string expected, got nil"

**Comment by unicuebbq** [comment]
I'm also having the issue; AR2 Log: Invalid ID provided when attempting to type /rare with a rare targeted.

**Comment by Alyred** [comment]
Same issue here, as posted above.

**Comment by destinychoice** [comment]
i think i found the issue, in AnnounceRare.lua line 669
replace 
`self:AnnounceRare()`
with 
`self:AnnounceRare(tarId, UnitHealth("target"), UnitHealthMax("target"))`

**Comment by Tequima** [comment]
TY @destinychoice works perfectly

**Comment by Alyred** [comment]
Works great!  Seems the announce death has a similar issue though.

**Comment by Alyred** [comment]
Yeah, so with the fix above, Announce won't work with debugging off (same error,does not qualify) but does work if debugging mode is enabled.
It's the opposite for announcing the death: Works when debugging is off, but doesn't when debugging is on -- the chat isn't clickable.

**Comment by GODLIKE-ro** [comment]
i still dont know why the developer isnt fixing the bugs yet

**Comment by programmerchad** [comment]
I submitted a PR to fix this, hopefully @cr4ckp0t sees it.  Also, I was able to get this working without debug by changing the line to this:

`self:AnnounceRare(tonumber(tarId), tonumber(UnitHealth("target")), tonumber(UnitHealthMax("target")))`

**Comment by cr4ckp0t** [comment]
You guys have to chill. I do not get paid to do any of the projects I have (roughly 20 or so), so I do them as I have time.

In any event, I had already fixed the issue but hadn't had time to commit and release it. Doing it now.

**Comment by Alyred** [comment]
Thanks, Cr4ckp0t.  Most of us are patient and only reporting to help out, understanding that life is busy and you're doing this for free.
Appreciate it.
