### ISSUE TITLE
/rare armory bugged 

### ISSUE THREAD

**Issue by Gershuun** [cr4ckp0t/AnnounceRare#3]
Getting this message with the latest build, when typing /rare armory 

> Message: ..\AddOns\AnnounceRare\AnnounceRare.lua line 138:
   attempt to index global 'coordString' (a nil value)
Debug:
   [C]: ?
   AnnounceRare\AnnounceRare.lua:138: ?()
   ..\FrameXML\ChatFrame.lua:4836:
      ..\FrameXML\ChatFrame.lua:4783
   [C]: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4497: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4533: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1

**Comment by cr4ckp0t** [comment]
Fixed in version 1.1.2.
