### ISSUE TITLE
available FRfr translation AND minor code fix about "/rare cache" command

### ISSUE THREAD

**Issue by Hefiz** [cr4ckp0t/AnnounceRare#30]
I fixed those things but I cant contribute directly as I'm not a project member.

[AnnounceRare_VGR.lua.txt](https://github.com/cr4ckp0t/AnnounceRare/files/5289904/AnnounceRare_VGR.lua.txt)
[frFR_VGR.lua.txt](https://github.com/cr4ckp0t/AnnounceRare/files/5289907/frFR_VGR.lua.txt)

Regards

**Comment by cr4ckp0t** [comment]
You can do a pull request. That I can then merge into the project. For localization, please use the addon's project page on CurseForge.
