### ISSUE TITLE
missing zone IDs

### ISSUE THREAD

**Issue by Hefiz** [cr4ckp0t/AnnounceRare#31]
it's impossible to announce Taspu (Uldum) as he's in the "chamber of stars" whose zone ID is different from Uldum's. The same is in the Vale with the green jade thing. I know the "debug" mode enables to see the zone id, but it doesn't work AFAIK.

**Comment by cr4ckp0t** [comment]
Turn debugging on then type "/rare zone" it will tell you the ID. If you can get me the ID, I can add it.
