### ISSUE TITLE
Feature Request: 9.0.1 map pin functionality.

### ISSUE THREAD

**Issue by Alyred** [cr4ckp0t/AnnounceRare#32]
Hello!  Thanks for the helpful addon, and looking forward to using it in Shadowlands.

Recently, there was a reddit post about a macro that can allow other players click to set a pin. Here's the post with screenshots:

https://www.reddit.com/r/wow/comments/jb5yjt/i_made_a_macro_to_quickly_help_others_by/

I think that this would be a fantastic addition to AnnounceRare's functionality using the new tools!

**Comment by cr4ckp0t** [comment]
I like this. I will see what I can do!

**Comment by cr4ckp0t** [comment]
It was an easy enough addition. Added in version 3.0.1. Thanks!
