### ISSUE TITLE
Possible update?

### ISSUE THREAD

**Issue by Kurisu68** [cr4ckp0t/AnnounceRare#34]
I found this addon incredibly helpful to the WoW community during BfA, and would love to carry on using it in the Shadowlands expansion.  I'm not a programmer, so I can't be sure how difficult it would be to add in the rare list (specifically the ones for the zone achievements)?

**Comment by EvilGrinUK** [comment]
I thought I'd give this a go. I have forked the project and added in some code to test. This seems to work so I have added a pull request that adds the maw zone rares.

https://github.com/cr4ckp0t/AnnounceRare/pull/35

If anyone wishes to test in the mean time they can check out my fork.

https://github.com/EvilGrinUK/AnnounceRare

**Comment by cr4ckp0t** [comment]
My apologies for the delay, things have been busy here so I have not had much chance to work on my addons.

I have merged the push request, and will release version 3.1.0. Thanks, @EvilGrinUK!
