### ISSUE TITLE
Add esMX Support

### ISSUE THREAD

**Issue by i5o** [cr4ckp0t/AnnounceRare#36]
Hey! Spanish also uses "Channel: Zone", please take a look at this comment I left on a diff addon on BFA

https://www.curseforge.com/wow/addons/rare-share?comment=47

I assume this would be the fix for this addon:
```lua
	return GetChannelName(
		(GetLocale() == "ruRU" or GetLocale() == "esMX") and channelRUFormat:format(general, zoneText) or channelFormat:format(general, zoneText)
	)
```

**Comment by i5o** [comment]
![image](https://user-images.githubusercontent.com/2650479/124330662-48d40880-db64-11eb-83a7-fb7d3497bfc0.png)

**Comment by cr4ckp0t** [comment]
Thanks, I will get it added to the next version.
