### ISSUE TITLE
No Chat Messages except Help & Settings

### ISSUE THREAD

**Issue by mrbryo** [cr4ckp0t/AnnounceRare#4]
Just not seeing any chat messages other than help and setting changes. When I click on a rare nothing happens. No error windows either. Let me know if you need anything.

**Comment by cr4ckp0t** [comment]
Did you try `/rare status`?

**Comment by mrbryo** [comment]
Yeah, sorry, status works as well.

![20190707_annouce_rare_status](https://user-images.githubusercontent.com/1635119/60785940-8cc4dc00-a109-11e9-98f6-465bd0dce269.jpg)

**Comment by cr4ckp0t** [comment]
I can already see the issue. You have /2 as your General channel. I am working on a way to determine what channel to print to.

**Comment by mrbryo** [comment]
I wish I knew how general got switched to /2...I'll research on how to switch it back.

**Comment by cr4ckp0t** [comment]
Try version 1.1.4. It should determine your general chat number automatically.

**Comment by mrbryo** [comment]
ok

**Comment by mrbryo** [comment]
Only one error came up. Here is what I got after loading it and clicking on the rare:

```
Date: 2019-07-08 20:40:13
ID: 1
Error occured in: Global
Count: 1
Message: SendChatMessage(): Channel send missing channel number
Debug:
   (tail call): ?
   [C]: ?
   [C]: SendChatMessage()
   ...nterface\AddOns\Ace3\AceComm-3.0\ChatThrottleLib.lua:434: SendChatMessage()
   AnnounceRare\AnnounceRare.lua:102:
      AnnounceRare\AnnounceRare.lua:95
   AnnounceRare\AnnounceRare.lua:138: ?()
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119
   [C]: ?
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:29:
      ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25
   ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:64: Fire()
   Ace3\AceEvent-3.0\AceEvent-3.0.lua:120:
      Ace3\AceEvent-3.0\AceEvent-3.0.lua:119
   [C]: CameraOrSelectOrMoveStop()
   [string "CAMERAORSELECTORMOVE"]:4:
      [string "CAMERAORSELECTORMOVE"]:1
Locals:
None
AddOns:
<removed to shrink error down - see attached file for whole text>
```
[20190708-annouce-rare-error.txt](https://github.com/cr4ckp0t/AnnounceRare/files/3371097/20190708-annouce-rare-error.txt)

**Comment by cr4ckp0t** [comment]
Update to 1.1.5 and let me know if it works for you.

**Comment by mrbryo** [comment]
Back to doing nothing. Status shows a little different. No errors.

![20190709_annouce_rare_status](https://user-images.githubusercontent.com/1635119/60950941-ee717b80-a2ac-11e9-823b-9385a57903d0.jpg)

**Comment by mrbryo** [comment]
Installed latest version and it is printing to general now. Appreciate the work!
