### ISSUE TITLE
LUA Error Upon Login with Addon Enabled

### ISSUE THREAD

**Issue by pavophobic** [cr4ckp0t/AnnounceRare#40]
Hello, @cr4ckp0t I love this addon- of all the similar addons I've seen, this by a wide margin is one of truly superior ones (and that I've only seen that actually provides a map ping). However, since the new update I've noticed a few errors when logging in, that seem to point to the Ace3 Library, please see below:

Message: ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
Time: Sun Aug  1 07:23:08 2021
Count: 1
Stack: ...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:7: Cannot find a library instance of "AceGUI-3.0".
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\AnnounceRare\Libraries\LibStub\LibStub.lua"]:38: in function `LibStub'
[string "@Interface\AddOns\AnnounceRare\Libraries\Ace3\AceConfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua"]:7: in main chunk

Locals: (*temporary) = "Cannot find a library instance of "AceGUI-3.0"."

Message: Interface\AddOns\AnnounceRare\AnnounceRare.lua:870: Cannot find a library instance of "AceConfigDialog-3.0".
Time: Sun Aug  1 07:23:08 2021
Count: 1
Stack: Interface\AddOns\AnnounceRare\AnnounceRare.lua:870: Cannot find a library instance of "AceConfigDialog-3.0".
[string "=[C]"]: in function `error'
[string "@Interface\AddOns\AnnounceRare\Libraries\LibStub\LibStub.lua"]:38: in function `LibStub'
[string "@Interface\AddOns\AnnounceRare\AnnounceRare.lua"]:870: in function <Interface\AddOns\AnnounceRare\AnnounceRare.lua:866>
[string "=[C]"]: ?
[string "@Interface\AddOns\AnnounceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...nceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\AnnounceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface\AddOns\AnnounceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua"]:623: in function <...nceRare\Libraries\Ace3\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

Message: (null)
Time: Sun Aug  1 07:23:23 2021
Count: 5
Stack: (null)

Locals: <none>

**Comment by pavophobic** [comment]
Could it be possibly the Library Loading Order? I was researching some possible instances of what might be happening- the addon actually works fine once the game starts, you only get the LUA error upon login; would this help?

`<Ui xmlns="http://www.blizzard.com/wow/ui/">
	<Script file="LibStub\LibStub.lua"/>
	<Script file="CallbackHandler-1.0\CallbackHandler-1.0.lua"/>
	<Include file="AceDB-3.0\AceDB-3.0.xml"/>
	<Include file="AceDBOptions-3.0\AceDBOptions-3.0.xml"/>
	<Include file="AceGUI-3.0\AceGUI-3.0.xml"/>
	<Include file="AceConfig-3.0\AceConfig-3.0.xml"/>
	<Script file="LibSharedMedia-3.0\LibSharedMedia-3.0.lua"/>
	<Include file="AceGUI-3.0-SharedMediaWidgets\widget.xml"/>
	<Include file="AceGUI-3.0-LSWidgets\_widgets.xml"/>`

**Comment by cr4ckp0t** [comment]
It's probably because he doesn't use any other addons that may include that library. I don't use the lib directly, but AceConfigDialog seems to, which I do use via AceConfig. I added it for the packager in version 3.2.9.
