### ISSUE TITLE
Consider hosting add-on here?

### ISSUE THREAD

**Issue by nezorflame** [cr4ckp0t/AnnounceRare#46]
Would you consider hosting the add-on here so those of us who wish to avoid Overwolf could do so?
It'd be nice to have the addon packaged as release ZIPs here to be supported by other package managers (e.g. [CurseBreaker](https://github.com/AcidWeb/CurseBreaker)).
Thank you!

Here's the conversation on another add-ons:
https://github.com/SLOKnightfall/BetterWardrobe/issues/250
https://github.com/davidmeen/TomeOfTeleportation/issues/14

**Comment by cr4ckp0t** [comment]
It honestly is on my list of things to do, but with so many addon projects I currently maintain it becomes difficult to find the time to actually do the dev work required to get this sort of thing setup. I hope to get it up and running on the projects I plan to maintain before the next xpac.
