### ISSUE TITLE
1.1.4 reporting not working.

### ISSUE THREAD

**Issue by LordDeimos666** [cr4ckp0t/AnnounceRare#5]
This commit 7712427 broke somewhat the report function.

Giving me this output:

`2x SendChatMessage(): Channel send missing channel number
[C]: ?
[C]: in function `SendChatMessage'
...ElvUI\Libraries\Ace3\AceComm-3.0-12\ChatThrottleLib-24.nil.lua:434: in function `SendChatMessage'
AnnounceRare\AnnounceRare-1.1.4.lua:102: in function <AnnounceRare\AnnounceRare.lua:95>
AnnounceRare\AnnounceRare-1.1.4.lua:138: in function `?'
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:119: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[C]: ?
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:29: in function <...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
...ies\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:64: in function `Fire'
...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0-4.lua:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>
[C]: in function `TargetNearestEnemy'
[string "TARGETNEARESTENEMY"]:2: in function <[string "TARGETNEARESTENEMY"]:1>`

**Comment by cr4ckp0t** [comment]
What channel number is your General channel? To talk in it what do you use? /1 /2 ?

**Comment by cr4ckp0t** [comment]
Also, what did you set the output to?

**Comment by SoulCookie** [comment]
I, also, am no longer getting any sort of announcement with 1.1.4.

- My general chat is `/1`
- Output is set to `General`. I even tried setting it to Guild then back to General; neither worked, either.
- Possibly relevant: I am also using ElvUI. But like I said, General chat is (and has been) /1 for me.

**Comment by cr4ckp0t** [comment]
I have a theory as to what it could be. Could you run "/rare output general" in game and then test it.

**Comment by SoulCookie** [comment]
`/rare output general` returns:

`AR: Changed output to GENERAL!`

**Comment by cr4ckp0t** [comment]
Does it announce rates correctly?

**Comment by SoulCookie** [comment]
It announces nothing under 1.1.4. 

1.1.3, in contrast, announced rares, deaths, etc., just fine.

**Comment by LordDeimos666** [comment]
> 
> 
> I, also, am no longer getting any sort of announcement with 1.1.4.
> 
>     * My general chat is `/1`
> 
>     * Output is set to `General`. I even tried setting it to Guild then back to General; neither worked, either.
> 
>     * Possibly relevant: I am also using ElvUI. But like I said, General chat is (and has been) /1 for me.

Same as him.

**Comment by cr4ckp0t** [comment]
It must have to do with how it has to search for general chat. My guess is you don't use en-US client? It looks for "general" in the chat name, so if it is different in your native client language, then it will fail every time. For 1.1.5 I am going to set it back to send it to channel 1 until I can figure out a better way to determine the general channel. Look for an update here in the next couple of minutes.

**Comment by monkaSad** [comment]
I'm using the European English (guessing that would be en-GB) Client and had the same issue

**Comment by SoulCookie** [comment]
> It must have to do with how it has to search for general chat. My guess is you don't use en-US client? 

I downloaded but haven't played with 1.1.5 yet, but just for troubleshooting: I _am_ using the **en-US** client.

**Comment by LordDeimos666** [comment]
> 
> 
> I'm using the European English (guessing that would be en-GB) Client and had the same issue

Same, en-GB client and the channel is number 1 and called "General" (case sensitive maybe?)

**Comment by Myst2222** [comment]
I have a similar issue but it ONLY effects manually triggered /rare calls. If I turn on the automatics it works fine. For manual calls, it fails irrespective of which channel I point it at.

**Comment by LordDeimos666** [comment]
> 
> 
> I have a similar issue but it ONLY effects manually triggered /rare calls. If I turn on the automatics it works fine. For manual calls, it fails irrespective of which channel I point it at.

1.1.5 same problem might be the same as i Use the macro /rare command, but that is my config printout:
![2019-07-10 15_06_54-Window](https://user-images.githubusercontent.com/21112906/60971510-a130f080-a324-11e9-9eb4-0655e2cbe52f.png)

**Comment by cr4ckp0t** [comment]
Okay, I think I have written a rather non-elegant, and frankly janky way to fix these non-reporting issues, but I am unable to test them since I am at work. In a moment I am going to push 1.1.6-beta to Curse, if someone can download it (may have to get it manually from Curse/Twitch) and give it a go.

I was able to login to the game to check for any immediate errors, but not able to actually able to check if it works correctly.

**Comment by LordDeimos666** [comment]
1.1.6 beta still same problem, working with auto mode enabled, using /rare doens't.

**Comment by cr4ckp0t** [comment]
Okay last time, try 1.1.6-beta2 that I just pushed to Curse/Twitch. It basically has the announcements done as a "catch all" for the chat command. I think that's why it wasn't doing anything when you entered the `/rare` command. At least the automatic announcements are working again. Let me know about the chat command and I'll release the final version.

**Comment by LordDeimos666** [comment]
I had literally to fly for 1 hour before finding a proper rare damn... And now it's ok, working as intended.

**Comment by Myst2222** [comment]
Working great for me again too. Love your work :)

**Comment by SoulCookie** [comment]
1.1.6 (release) appears to have returned almost all of the announcing functionality. Thanks!

One issue I'm seeing is that **I can no longer manually call `/rare` on a mob more than once.** 

My use-case for that has been to do one `/rare` call when I arrive at an unengaged mob, then do a second one when the mob is actually engaged. Kind of a _"come here!"_ and _"better hurry!"_ pairing.

**Comment by SoulCookie** [comment]
Do you want me to submit the _double-`/rare` no longer working_ thing as a new issue? Or are you considering it not a bug?

**Comment by cr4ckp0t** [comment]
Nah, it is working as intended but I have changed it to where you can do it once again.
