### ISSUE TITLE
Rare(s) INSIDE Obsidian Citadel are found but can not be announced

### ISSUE THREAD

**Issue by fubaWoW** [cr4ckp0t/AnnounceRare#51]
hi there,

2 Rares that spawn INSIDE the Obsidian Citadel (downstairs) are found by the AddOn but click on the chat text does not announce them.
I think this is because INSIDE the Obsidian Citadel is a "unknown/wrong" Zone or Zone ID?

Rares that does not work are:
[Shas'ith](https://www.wowhead.com/npc=189822)
[Rasnar the War Ender](https://www.wowhead.com/npc=193232)

**Comment by cr4ckp0t** [comment]
Fixed in [7ee4da9](https://github.com/cr4ckp0t/AnnounceRare/commit/7ee4da9abf0709b39cad44e6c6690a6e3d7fcdb8).
