### ISSUE TITLE
Missing Rare: Qalashi War Mammoth at The Waking Shores

### ISSUE THREAD

**Issue by fubaWoW** [cr4ckp0t/AnnounceRare#52]
hi there, again ^^

the [Qalashi War Mammoth](https://www.wowhead.com/npc=192737) with the ID ``192737`` is also missing in the DB.

**Comment by cr4ckp0t** [comment]
Fixed in [7ee4da9](https://github.com/cr4ckp0t/AnnounceRare/commit/7ee4da9abf0709b39cad44e6c6690a6e3d7fcdb8).
