### ISSUE TITLE
Request - Waypoint arrows

### ISSUE THREAD

**Issue by Myst2222** [cr4ckp0t/AnnounceRare#6]
Hi. I was testing this today when i had a rare spawn outside of target range. Currently that often means me finding the rare in the Tomcat's Tours list, to get an arrow to lead me there. I was thinking it would be great if when out of target range of a rare, if instead you could click and bring up a tomtom pointer leading you to them. I am not a coder, so I have no idea if this is a 5 minute thing, or a 'cannot change the laws of physics' type of request. :)

**Comment by cr4ckp0t** [comment]
The API would not allow for that since this is based on your target and getting information about it. Sorry.
