### ISSUE TITLE
You must be in Mechagon or Nazjatar to use this command.

### ISSUE THREAD

**Issue by Rawrjay** [cr4ckp0t/AnnounceRare#8]
I'm in Nazjatar.. 
![World Of Warcraft Screenshot 2019 07 11 - 16 16 30 66](https://user-images.githubusercontent.com/18626710/61091942-02c28f00-a3f9-11e9-8f1c-d3bc1ee622fd.png)

**Comment by cr4ckp0t** [comment]
I think I know why it did that. I have fixed it in 1.1.7 coming later tonight.

**Comment by StragaSevera** [comment]
+1, have the same problem

**Comment by cr4ckp0t** [comment]
Test out 1.1.7 (just pushed to Curse/Twitch, sorry for the delay) and let me know if it is working for you.

**Comment by AnonBit** [comment]
1.1.7 not fixed yet

**Comment by cr4ckp0t** [comment]
It's because you're in a caved and that changes the zone to something other than Nazjatar or Mechagon. I don't know of a way to fix it other than getting the names of all of the caves and that does not sound like something I'd want to do. I'll look into it more and see if I can find a workaround.

**Comment by cr4ckp0t** [comment]
It's because the cave has a different location not containing Nazjatar. I am going to do it by map ID and see if that corrects the issue. 1.1.8 will be out today.

**Comment by cr4ckp0t** [comment]
Okay, it is now done by the map ID, so it should no longer misbehave. It worked in the cave when i was in there.

**Comment by AnonBit** [comment]
Now seems to be ok. 
But there other bug command "/rare armory" not work

**Comment by cr4ckp0t** [comment]
/rare armory no longer announces armories. That is done automatically when you mouseover an armory's anti-grav pack.
