### ISSUE TITLE
The /rare armory - Command does not send to the output channel set by /rare output.

### ISSUE THREAD

**Issue by Sinnoh** [cr4ckp0t/AnnounceRare#9]
Version: 1.1.7

The /rare armory - Command does not send to the output channel set by /rare output. Instead it always announces to general chat.

Expected behaviour: The /rare armory - Command always announces to the channel set by /rare output. This would make it's behaviour more consistent with that of /rare and /rare death

**Comment by cr4ckp0t** [comment]
Armory announcements are now automatic when you mouseover the anti-grav pack (armory must be constructed). I am trying to figure out a way to automatically announce an armory not yet built.
